# @EclipseWorks.AdminTarefas.Api_HostAddress = http://localhost:5454
@EclipseWorks.AdminTarefas.Api_HostAddress = https://localhost:7008

### CriarProjeto
POST {{EclipseWorks.AdminTarefas.Api_HostAddress}}/projetos
Accept: application/json
Content-Type: application/json

{
  "nomeProjeto": "Meu Contador",
  "IdUsuario": "2e197f3f-a9d0-48f8-a893-7077677b32ca"
}

### ProjetosPorUsuario
GET {{EclipseWorks.AdminTarefas.Api_HostAddress}}/projetos/2e197f3f-a9d0-48f8-a893-7077677b32ca
Accept: application/json
Content-Type: application/json

### CriarTarefa
POST {{EclipseWorks.AdminTarefas.Api_HostAddress}}/tarefas
Accept: application/json
Content-Type: application/json

{
  "IdProjeto": "c56b501e-7bb0-41e1-b8a4-f82a475e0065",
  "Titulo": "Criar Front-End",
  "Descricao": "Time de Front-End desenvolver aplicação Angular",
  "DataVencimento": "2024-03-16",
  "IdStatus": 1,
  "IdPrioridadeTarefa": 1,
  "IdUsuario": "2e197f3f-a9d0-48f8-a893-7077677b32ca"
}

### TarefasPorProjeto
GET {{EclipseWorks.AdminTarefas.Api_HostAddress}}/tarefas/c56b501e-7bb0-41e1-b8a4-f82a475e0065
Accept: application/json
Content-Type: application/json

### AtualizarTarefa
PUT {{EclipseWorks.AdminTarefas.Api_HostAddress}}/tarefas/4d1e593d-fe0b-4329-b45f-569839b5caf5
Accept: application/json
Content-Type: application/json

{
  "Titulo": "Criar Front-End 2",
  "Descricao": "Time de Front-End desenvolver aplicação Angular 2",
  "IdStatus": 2,
  "IdUsuario": "2e197f3f-a9d0-48f8-a893-7077677b32ca"
}

### RemoverTarefaProjeto
DELETE {{EclipseWorks.AdminTarefas.Api_HostAddress}}/tarefas/4d1e593d-fe0b-4329-b45f-569839b5caf5
Accept: application/json
Content-Type: application/json

### MediaTarefasConcluidasPorUsuarios
GET {{EclipseWorks.AdminTarefas.Api_HostAddress}}/tarefas/relatorio/media-diaria-conclusao/2e197f3f-a9d0-48f8-a893-7077677b32ca
Accept: application/json
Content-Type: application/json

### AdicionarComentarioTarefa
POST {{EclipseWorks.AdminTarefas.Api_HostAddress}}/tarefas/adicionar-comentario
Accept: application/json
Content-Type: application/json

{
  "IdTarefa": "4d1e593d-fe0b-4329-b45f-569839b5caf5",
  "Comentario": "Tarefa atrasando",
  "IdUsuario": "2e197f3f-a9d0-48f8-a893-7077677b32ca"
}