// <auto-generated />
using System;
using EclipseWorks.AdminTarefas.DataAccess.EfContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EclipseWorks.AdminTarefas.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.LogAlteracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Campo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("DataHoraModificacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdEntidade")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valor")
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar(550)");

                    b.HasKey("Id");

                    b.ToTable("LogAlteracao", (string)null);
                });

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.PrioridadeTarefa", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("PrioridadeTarefa", (string)null);
                });

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Projeto", (string)null);
                });

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.StatusTarefa", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("StatusTarefa", (string)null);
                });

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("DATE");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdPrioridadeTarefa")
                        .HasColumnType("int");

                    b.Property<Guid>("IdProjeto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdPrioridadeTarefa");

                    b.HasIndex("IdProjeto");

                    b.HasIndex("IdStatus");

                    b.ToTable("Tarefa", (string)null);
                });

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.Projeto", b =>
                {
                    b.HasOne("EclipseWorks.AdminTarefas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Projetos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("EclipseWorks.AdminTarefas.Domain.Entities.PrioridadeTarefa", "PrioridadeTarefa")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdPrioridadeTarefa")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EclipseWorks.AdminTarefas.Domain.Entities.Projeto", "Projeto")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdProjeto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EclipseWorks.AdminTarefas.Domain.Entities.StatusTarefa", "StatusTarefa")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PrioridadeTarefa");

                    b.Navigation("Projeto");

                    b.Navigation("StatusTarefa");
                });

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.PrioridadeTarefa", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.Projeto", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.StatusTarefa", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("EclipseWorks.AdminTarefas.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Projetos");
                });
#pragma warning restore 612, 618
        }
    }
}
